### ISSUE TITLE
Checkout my KiCAD project of a fixed GPIO pcb

### ISSUE THREAD

**Issue by nobodypb** [Pi-Case-40-Community/Pi-Case-40#1]
Hi, I've layouted a modified version of the built-in pcb in KiCAD to change the rows order and just uploaded it as OpenSource: https://github.com/nobodypb/PiCase40-GPIO
Feel free to include it here and/or use it as you like.
It's not tested yet, but I'm confident it's mostly correct. The only thing that concerns me by now is the pcb thinkness.
I'll update my README after I recieve my ordered boards.

**Comment by ifohancroft** [comment]
Hey! Thanks for sharing this! I'll upload it right now.

**Comment by ifohancroft** [comment]
P.S. I am also working on a fix for it and I also have doubts about the PCB height because of how they've made theirs.
