### ISSUE TITLE
Please link my repository

### ISSUE THREAD

**Issue by nobodypb** [Pi-Case-40-Community/Pi-Case-40#2]
Could you please add a link to my repository somewhere? 
As I'll update my WIP there and push to this project after reaching a certain milestone. 
It might be interesting for others to watch the progress.

**Comment by ifohancroft** [comment]
Yeah, of course. I was thinking about having links to people's repos might be a good idea but forgot to tell you about it.
I'll add it at the bottom of your PCB's README file, just so you know, so you don't override it when updating the README for example.

**Comment by ifohancroft** [comment]
Done.
